steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/wikipdf",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/wikipdf"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "wikipdf",
        "--image","gcr.io/$PROJECT_ID/wikipdf",
        "--platform","managed",
        "--region", "europe-west1",
        "--allow-unauthenticated",
      ]
timeout: "300s"
